version: '3.2'

services:
  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: be.heydari.contentcloud.domaingenerator.keycloak
      DB_USER: be.heydari.contentcloud.domaingenerator.keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: be.heydari.contentcloud.domaingenerator.keycloak
      POSTGRES_USER: be.heydari.contentcloud.domaingenerator.keycloak
      POSTGRES_PASSWORD: password

  opa:
    image: openpolicyagent/opa:0.20.5
    ports:
      - "8181:8181"
    command: "run --server --log-level=debug --bundle /policies"
    volumes:
      - ./account-state-service/src/main/resources:/policies

  solr:
    image: paulcwarren/solr
    ports:
      - "8983:8983"

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG

volumes:
  postgres-data: {}