version: '3.2'

services:
  keycloak:
    image: jboss/keycloak:7.0.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_USER: keycloak
      DB_PASSWORD: p@ssword
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: p@ssword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  opa:
    image: openpolicyagent/opa:0.20.5
    ports:
      - "8181:8181"
    command: "run --server --log-level=debug --bundle /policies"
    volumes:
      - ./account-state-service/src/main/resources:/policies

  solr:
    image: paulcwarren/solr
    ports:
      - "8983:8983"

volumes:
  postgres-data: {}