version: '3.2'

services:
  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - postgres-keycloak

  postgres-keycloak:
    image: postgres
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

#  sqlserver-account-state:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    environment:
#      ACCEPT_EULA: Y
#      SA_PASSWORD: s3cr3t_p@ssw0rd
#    ports:
#      - "1433:1433"
#    volumes:
#      - sqlserver-account-state-data:/var/opt/mssql/

  postgres-account-state:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-account-state-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: account-state
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  opa:
    image: openpolicyagent/opa:0.20.5
    ports:
      - "8181:8181"
    command: "run --server --log-level=debug"
  #    command: "run --server --log-level=debug --bundle /policies"
  #    volumes:
  #      - ./account-state-service/src/main/resources:/policies

  policy-pusher:
    image: contentcloudpoc.azurecr.io/policy-pusher
    environment:
      PDP_ADDR: opa:8181
    restart: on-failure
    volumes:
    - ./opa/src/main/resources/:/resources
    depends_on:
      - opa

  solr:
    image: paulcwarren/solr
    ports:
      - "8983:8983"

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment to enable debug logging
      # command: --logging.level.zipkin2=DEBUG

volumes:
  postgres-keycloak-data: { }
  postgres-account-state-data: { }
  sqlserver-account-state-data: { }