from openjdk:15-jdk-alpine
copy opa/target/opa-0.0.1-SNAPSHOT-jar-with-dependencies.jar app.jar
copy opa/src/main/resources resources
env POLICY_FILE=/resources/query/policies.rego

entrypoint ["java", "-jar", "app.jar"]