# https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: fill-keycloak
spec:
  template:
    spec:
      containers:
        - name: fill-keycloak
          image: content-cloud/domain-generator
          imagePullPolicy: Never
          env:
            - name: KEYCLOAK_ADDR
              value: keycloak:8080
      restartPolicy: Never # replace by OnFailure once sure that working
  backoffLimit: 10