apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      imagePullSecrets:
        - name: azurecrcred
      containers:
        - name: locust-worker
          image: contentcloudpoc.azurecr.io/locust
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          command: [ "locust", "-f", "main.py", "--worker", "--master-host", "locust-master" ]