apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  labels:
    app: zikpin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: ghcr.io/openzipkin/zipkin-slim:latest
          ports:
            - containerPort: 9411
          env:
            - name: STORAGE_TYPE
              value: mem
