#configuration for the account state service with an embedded database
accountState:
  mode: "hardcoded"
  dbDriver: H2
  dbRecordCount: "\"10000\""
cluster:
  k8s: "AKS"
zipkin:
  sampleRate: "\"0\""