apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-pusher-config
data:
  POLICY_LANGUAGE: {{ .Values.pdp.lang }}
  PDP_ADDR: {{ .Values.pdp.host }}
  {{ if eq .Values.pdp.lang "Rego" -}}
  POLICY_FILE: {{ .Values.pdp.policyFile }}
  {{ else if eq .Values.pdp.lang "Java" -}}
  POLICY_NAME: {{ .Values.pdp.policyName }}
  {{ end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: policy-pusher
spec:
  template:
    spec:
      {{ if eq .Values.cluster.k8s "minikube" -}}
      imagePullSecrets:
        - name: azurecrcred
      {{end -}}
      {{ if eq .Values.cluster.k8s "AKS" -}}
      nodeSelector:
          agentpool: application
      {{end -}}
      containers:
        - name: policy-pusher
          image: contentcloudpoc.azurecr.io/policy-pusher
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: policy-pusher-config
      restartPolicy: Never
  backoffLimit: 10
