server:
  port: 8070

spring:
  sleuth:
    sampler:
      probability: ${ZIPKIN_SAMPLING_RATE:1.0}
    enabled: true
  zipkin:
    base-url: http://${ZIPKIN_ADDR:127.0.0.1:9411}
    service:
      name: "acc-state"
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_ADDR:localhost:8080}/auth/realms/content-cloud-realm
