apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      name: gateway
      port: 8060
      targetPort: 8060
    {{ if eq .Values.experiment.fgac "query" -}}
    - protocol: TCP
      name: opa
      port: 8181
      targetPort: 8181
    {{- end -}}