apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-config
data:
  POLICY_LANGUAGE: {{ .Values.pdp.lang }}
  PDP_ADDR: {{ .Values.pdp.host }}
  {{ if eq .Values.pdp.lang "Rego" -}}
  POLICY_FILE: {{ .Values.pdp.policyFile }}
  {{ else if eq .Values.pdp.lang "Java" -}}
  POLICY_NAME: {{ .Values.pdp.policyName }}
  {{ end }}
