apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-state-deployment
  labels:
    app: account-state
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-state
  template:
    metadata:
      labels:
        app: account-state
    spec:
      imagePullSecrets:
        - name: azurecrcred
      containers:
        - name: account-state
          image: contentcloudpoc.azurecr.io/account-state-query
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
          envFrom:
            - configMapRef:
                name: account-state-config