apiVersion: v1
kind: Service
metadata:
  name: account-state
spec:
  selector:
    app: account-state
  ports:
    - protocol: TCP
      name: account-state
      port: 8070
      targetPort: 8070
    {{ if eq .Values.fgac "postfilter" -}}
    - protocol: TCP
      name: opa
      port: 8181
      targetPort: 8181
    {{- end -}}