apiVersion: v1
kind: ConfigMap
metadata:
  name: account-state-config
  labels:
    app: account-state
data:
  KEYCLOAK_ADDR: {{ .Values.keycloak.addr }}
  ZIPKIN_ADDR: {{ .Values.zipkin.addr }}
  ZIPKIN_SAMPLE_RATE: {{ .Values.zipkin.sampleRate }}
  DB_DRIVER: {{ .Values.db.driver }}
  DB_SERVER: {{ .Values.db.server }}
  DB_NAME: {{ .Values.db.name }}
  DB_USER: {{ .Values.db.user }}
  DB_PASSWORD: {{ .Values.db.password }}
  DB_RESET: {{ .Values.experiment.resetDB }}
  DB_RECORD_COUNT: {{ .Values.experiment.accountStateCount }}
  DB_BROKER_COUNT: {{ .Values.experiment.brokerCount}}
