apiVersion: v1
kind: ConfigMap
metadata:
  name: account-state-config
  labels:
    app: account-state
data:
  KEYCLOAK_ADDR: keycloak:8080
  ZIPKIN_ADDR: zipkin:9411
  ZIPKIN_SAMPLE_RATE: {{ .Values.zipkin.sampleRate }}
  DB_DRIVER: {{ .Values.accountState.dbDriver }}
  DB_SERVER: {{ .Values.accountState.dbServer }}
  DB_NAME: {{ .Values.accountState.dbName }}
  DB_USER: {{ .Values.accountState.dbUsername }}
  DB_PASSWORD: {{ .Values.accountState.dbPassword }}
  DB_RECORD_COUNT: {{ .Values.accountState.dbRecordCount }}
