{{ if eq .Values.accountState.dbDriver "MSSQL" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      # run as root, otherwise the container will not start
      # since it tries to create the "/.systems" folder
      # but has no rights to do so. (for some reason this is no issue in docker-compose)
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          envFrom:
            - configMapRef:
                name: mssql-config
          volumeMounts:
            - mountPath: /var/opt/mssql/
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-pv-claim
{{ end }}