{{ if eq .Values.db.driver "MSSQL"}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.accountState.dbServer }}
  labels:
    app: mssql
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
{{ end -}}