{{ if eq .Values.accountState.dbDriver "Postgres" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-state-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-state-postgres
  template:
    metadata:
      labels:
        app: account-state-postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: account-state-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: account-state-postgresdb
      volumes:
        - name: account-state-postgresdb
          persistentVolumeClaim:
            claimName: account-state-postgres-pv-claim
{{ end }}