{{ if eq .Values.accountState.dbDriver "Postgres" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: account-state-postgres-pv-volume
  labels:
    type: local
    app: account-state-postgres
spec:
  # change to the actual storage class once going to aks: https://kubernetes.io/docs/concepts/storage/storage-classes/
  # https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv
  # https://docs.microsoft.com/en-us/azure/aks/azure-disk-volume
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/account-state/postgres/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: account-state-postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{ end }}