apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
  labels:
    app: locust
data:
  LOCUST_HEADLESS: {{ .Values.locust.headless }}
  {{ if eq .Values.locust.headless "\"True\"" -}}
  LOCUST_HOST: {{ .Values.locust.host }}
  LOCUST_USERS: {{ .Values.experiment.users }}
  LOCUST_SPAWN_RATE: {{ .Values.experiment.spawnRate}}
  LOCUST_RUN_TIME: {{ .Values.experiment.runTime }}
  LOCUST_CSV: "{{ .Values.locust.statsDir }}/latencies"
  LOCUST_CSV_FULL_HISTORY: {{ .Values.locust.csvFullHistory }}
  CLIENT_BROKER_COUNT: {{ .Values.experiment.brokerCount }}
  CLIENT_ACTIVE_BROKER_COUNT: {{ .Values.experiment.activeBrokerCount }}
  CLIENT_PAGE_SIZE: {{ .Values.experiment.pageSize }}
  CLIENT_USER_RPS: {{ .Values.experiment.userRPS }}
  CLIENT_ENABLE_HISTORY_DB: {{ .Values.locust.enableHistoryDB }}
  CLIENT_HISTORY_DB_FILE: "{{ .Values.locust.statsDir }}/latencies.sqlite"
  {{- end }}