apiVersion: v1
kind: Service
metadata:
  name: locust
spec:
  selector:
    app: locust
  ports:
    - name: web-interface
      protocol: TCP
      port: 8089
      targetPort: 8089
    - name: master-worker-interface
      protocol: TCP
      port: 5557
      targetPort: 5557